analyzer:
  errors:
    use_build_context_synchronously: ignore
    invalid_annotation_target: ignore
    library_private_types_in_public_api: ignore

include: package:flutter_lints/flutter.yaml

linter:

  rules:
    prefer_relative_imports: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
